DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY(name)
);

DROP TABLE IF EXISTS openpaths;
CREATE TABLE openpaths (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER NOT NULL,    
    time DATETIME NOT NULL,
    lat VARCHAR(255) NOT NULL,
    lon VARCHAR(255) NOT NULL,    
    alt VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY(user_id),
    UNIQUE KEY time_location (user_id, time, lat, lon),
    KEY(time)    
);

DROP TABLE IF EXISTS labels;
CREATE TABLE labels (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    label VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY(user_id)        
);